modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/NoPlanCoders/IdolCraft/issues"

[[mods]]
modId="gakumas_produce"
version="1.0.0"
displayName="Gakumas Produce"
authors="NoPlanCoders"
description='''
Gakumas-style produce card and buff system for Minecraft Forge 1.20.1.
'''

[[dependencies.gakumas_produce]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gakumas_produce]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
