modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/NoPlanCoders/IdolCraft/issues"

[[mods]]
modId="idolcraft"
version="1.0.0-beta"
displayName="IdolCraft"
authors="NoPlanCoders"
description='''
Gakumas-style produce card and buff system for Minecraft Forge 1.20.1.
'''
displayURL="https://github.com/NoPlanCoders/IdolCraft"

[[dependencies.idolcraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.idolcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
